### ISSUE TITLE
Вывод "Прошлая неделя" вместо "Следующая неделя"

### ISSUE THREAD

**Issue by kajr0s** [leaftail1880/xdnevnik#42]
Баг стал проявляться после дня использования. Хотя при нажатии работает правильно - переходит на следующую неделю.

![Screenshot_20241224_125343_Arseniy](https://github.com/user-attachments/assets/0f834ecf-c1c7-4312-8f2a-c0be79a7a135)

**Comment by leaftail1880** [comment]
А, спасибо, это моя невнимательность, забыл поменять текст

Баг пофикшен, щас остальные посмотрю и релиз сделаю
