### ISSUE TITLE
В режиме оценок выводит данные за всю неделю

### ISSUE THREAD

**Issue by kajr0s** [leaftail1880/xdnevnik#43]
Может быть стоит выводить оценки **только** на _просматриваемую_ дату?

В прикреплённом изображении выделено два домашних задания (на понедельник и вторник). В данном случае мы находимся на понедельнике, а сейчас уже вторник.

Прошу добавить функционал фильтра оценок...

Самое простое - сделать несколько галочек для оценок:
1. фильтр по всей неделе (как сейчас)
2. фильтр "только _просматриваемая_ дата"
3. фильтр "_просматриваемая_ и все _предыдущие_ на этой неделе"

![Screenshot_20241224_125222_Arseniy](https://github.com/user-attachments/assets/7a75d843-b8c6-44de-87ef-1ee098a2f821)

**Comment by leaftail1880** [comment]
По задумке оно должно показывать задания только для конкретного дня, просто фильтр неправильно реализован (он выдает оценки либо за конкретный урок, либо все оценки без веса за день урока. Я не помню уже почему второй случай когда-то нужен и почему в других учебных заведениях оно не вызывало проблем, но думаю пока отключу его, если починит баг будет хорошо)

**Comment by leaftail1880** [comment]
Микрообновление с фиксом опубликовано! (https://github.com/leaftail1880/xdnevnik/actions/runs/12481053788/job/34832898032)

Чтобы обновиться, перейдите в Настройки -> Обновления -> Сборка. Затем нажмите проверить наличие микрообновлений
(Для обновления нужна версия приложения 0.17.0)

**Comment by leaftail1880** [comment]
Насчет фильтров дз по неделям/дням - это планируется сделать на отдельном экране "Инструменты" вместе с другими вещами. Полный план нововведений можно посмотреть тут: #41
