### ISSUE TITLE
В режиме оценок домашние задания и оценки по предметам не поддаются логике

### ISSUE THREAD

**Issue by kajr0s** [leaftail1880/xdnevnik#44]
Например, просматриваю понедельник, но сейчас уже вторник.

В предмете "Математика" вижу домашнее задание по предмету "Русский язык" за вторник.
В предмете "Математика" вижу ответы на уроке по биологии.

![Screenshot_20241224_125323_Arseniy](https://github.com/user-attachments/assets/cc3dad5a-0613-4252-9fa1-42832a99c24b)

**Comment by leaftail1880** [comment]
Та же причина, что и в #43
